pipeline {
    agent any

    environment {
       IMAGE = "maven-app"
       VERSION = "1.0.${env.BUILD_ID}"
    }

    stages {

      stage('Check out') {
        steps {
          checkout scm
        }
      }

      stage('Build Application'){
        steps {
           script {
            sh """
            cd devops-dummy-apps/maven/demo
            mvn clean package
            """
          }
        }
      }
      stage('Docker build'){
        steps {
           script {
            sh """
            cd devops-dummy-apps/maven/demo
            sudo docker build -t ${IMAGE}:${VERSION} .
            sudo docker images
            """
          }
        }
      }
      stage('Docker Images'){
        steps {
           script {
            sh """
            sudo docker images
            """
          }
        }
      }
      stage('deployment dev'){
        steps {
           script {
            sh """
            sudo docker run -it -d -p 8081:8080 ${IMAGE}:${VERSION}
            """
          }
        }
      }
      stage('deployment stage'){
        steps {
           script {
            sh """
            sudo docker run -it -d -p 8082:8080 ${IMAGE}:${VERSION}
            """
          }
        }
      }
  }
}