pipeline {
    agent any

    environment {
       IMAGE = "reponame"
       VERSION = "1.0.${env.BUILD_ID}"
    }

    stages {

      stage('Check out') {
        steps {
          checkout scm
        }
      }

      stage('Build Application'){
        steps {
           script {
            sh """
            cd devops-dummy-apps/maven/demo
            mvn clean package
            """
          }
        }
      }
    }
}
